
# delete logs older than 7 days
Get-ChildItem �Path  "\\HOSTNAME\Deploy\Logs\*.log" �Recurse | ? { $_.CreationTime �lt (Get-Date).AddDays(-7) } | foreach($_) { Remove-Item $_.FullName -Force }

 Get-ChildItem -Path "C:\Work\*" -Include "*.cmd" -Exclude "Scripts" | foreach ($_) { Write-Host $_.fullName }

 $job = Invoke-Command -ScriptBlock { iisreset / STATUS } -Credential sbintl\svc_win_dev -ComputerName HOSTNAME -AsJob
 $result = $job | Format-List
 Write-Output ($result)


 Get-WmiObject Win32_Product | Select-Object Name, Version, Vendor | Sort-Object Name | ConvertTo-Html | Out-String

 Cls
 function Send-Email
 {
     Param(  [ValidateNotNullOrEmpty()] [string] $Subject, [ValidateNotNullOrEmpty()] [string] $Body )
     $footer = "<br><br><hr><small>This is autogenerated email from {1} by {2} at {0}.</small>" -f $(Get-Date), $env:ComputerName, $env:UserName 
     $messageParams = @{
             SmtpServer = 'smtp.gmail.co.uk'
             From = "TeamCity Build <noreply@gmail.com>"
             To = "Kiran Kurapaty <kurapaty@gmail.com>"
             Body = "{0} {1}" -f $Body, $footer 
             Subject = $Subject
     }
     try
     {
         Send-MailMessage @messageParams -BodyAsHtml -DeliveryNotificationOption OnFailure,OnSuccess -ErrorAction SilentlyContinue
         Write-Host "Email Sent: $Subject" 
     }
     catch
     {
         Write-Host "Unable to send email: $Subject"
     }
 }
 
 Send-Email -Subject "Test Subject" -Body "This is a test email, please ignore."
 
      
 $footer = "<br><br><hr><small>This is autogenerated email from {1} by {2} at {0}.</small>" -f $(Get-Date), $env:ComputerName, $env:UserName 
 $body = Get-WmiObject Win32_Product | Select-Object Name, Version, Vendor | Sort-Object Name | ConvertTo-Html | Out-String             
$messageParameters = @{                        
           Subject = "Software Installed on $env:ComputerName.$env:USERDNSDOMAIN - $((Get-Date).ToShortDateString())"                        
           Body =  "{0} {1}" -f $body, $footer
          # Body = gsv CAM*.* -ComputerName CIBLDNGAPPVD058 |  ConvertTo-Html | Out-String
           From = "$env:USERNAME@gmail.com"                        
           To = "kkurapaty@gmail.com"                        
           SmtpServer = "smtp.gmail.co.uk"                        
       }                        
       Send-MailMessage @messageParameters -BodyAsHtml   
 